# Basic appveyor configuration : CodeCakeBuilder does the job.
version: build{build}
branches:
  only:
  - master
  - develop
environment:
  MYGET_PREVIEW_API_KEY:
    secure: Nv4GSsLfg6rlnrNN/d5f0mUiE9x/LFmeT/vuY+JkT7rIoSVMnw8BNy1hdRqMzJHq
  MYGET_CI_API_KEY:
    secure: +XJ4LTAkcGevClWSYf0MsWpZfOGBLFSC6wJMyXC3sdnp5JZCzckPx1qvfoi8vP4d
  REGISTRY_AUTH_TOKEN:
    secure: eVOVWzwhTnv2FFAZNrzvLljWqB27u/XNB+WyvknPicmwVTPDOg/yACqd0CxnKcXd6/a3n4yhoRRk0ExzznqQNuFYEuc4La0zMuOlZeyrT0k2ECUu92lVqsbDhQATqrB2P1VIUlQeBfw/y6g880yBaaR8AZay2nbujv6oBIcXd71cHrntxrz+zNJ3lHtg1VedW3HRtuHckQfW0M3CoQPHHp17u0FIYnEoIjBeVDX+ZFnFavZsWDzc475965q++wNl2FguYeGkRCniFU9lwZjnBa1KdDbtb2ZSR+AFsDC/W+yevAT4/x8dRbmhjpCi5ghAqaFi6hfprQjI+1p8FdSy4KtDAGRq68prfbHCFKyPuR1gTYk9nH4tQifdFyU3DavejDPU3qjWczIBJuNNNeipbDMQNfk/R2TPlsDjef4qvKZ/TkWJr6+WpHK1WKEIeeARS62uiHbB7DVQij2gCJtqplR0Fr7yfY7mG1WNDPzGsws32Agbw6uSDqqFsJPgembbqvW9sFg4ns22Pd4WEKTuBKzWri5PLzG6xiHaTDbEz+S3VwkfRrWrEOnpWW1K6Yd4Z4tfneLclDyMEE94gbhvrIKtux6STgTQUvO7Ih5fXC5StAg7ULyHHBb5uYKYVgPA7C/AZO+qMXB2UJd9UcmGvI3vq2WGzk93ovECEEy8gCrjZ/0lrWki7IIkvPz+tdMGfp3j56HafsuMTChgrTgLWNvNhIxWZKy2gTou4Nw/5KrtNIcl7v11HpYtak099xHJ+Xc75Yhj7mxhdsJjL9B+ti0Jdc5tzjwMPkjKg+bx5Emx6heEF4qv0wy/Ukcr+2rtz8p6iJtwOAXiQtKLd+tJfvS4Ury/8jP+cLiHRLiaGBRf2CY/RJh3FyeCdiAgbq1qiAs9YMbFfn9M3sr0otyy08qO2XDPTtO2iwyFij20EivSs6QQ+76h6ue6cyS4Lbll/9G8C127BE35feZAGgXoxm22MNo4dZJSo8CZq6Nn/uWESCD+JXiUUCjwSCFgWft3al5vcmyRKnkaPjseJofEC7sJWqqa3OA8tYW89WQPDkXdO8mwBU5HwDP/K5CiHoI3TJyN658ZCcqvWxGAoIJCLTttudExo4kQ+oZrbbEc5NN45QvlD2fabwO43NIdX691o0cZlJGd7UCvdI+BVunlRg==

init:
- git config --global core.autocrlf true
install:
  - ps: CodeCakeBuilder\Bootstrap.ps1
  - ps: CodeCakeBuilder\AddNpmrc.ps1
build_script:
- CodeCakeBuilder\bin\Release\CodeCakeBuilder.exe -nointeraction
test: off
